### PR TITLE
Update for SilverStripe\CMS namespace

### PR DESCRIPTION
**Pull request by tractorcow**
For https://github.com/silverstripe/silverstripe-cms/issues/1572

### CODE REVIEW

**Comment by dhensby** [comment]
Seems like there's a bug in the test suite?

**Comment by tractorcow** [comment]
PHP7 should be allowed failure I think.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/issues/5886

**Comment by dhensby** [comment]
> PHP7 should be allowed failure I think.

It should

**Pull request merged**
